"""
svgutil.py -- small vector toolkit for the SuperteamTR T-Shirt design package.

Everything the artwork generator needs:
  * a tiny SVG document builder
  * geometry helpers (circles / rings / arcs / rounded "arch" portals) that emit
    FILLED paths only (no strokes) -> 100% screen-print safe, easy separations
  * text -> outline paths via HarfBuzz shaping + fontTools glyph outlines
  * official brand SVG import (paths + transforms + gradients) so the supplied
    logo files are used unmodified
"""
from __future__ import annotations

import math
import os
import re
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field

import uharfbuzz as hb
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.misc.transform import Transform
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

from .pathparse import transform_d as _transform_d

INK_SOLANA_PURPLE = "#9945FF"
INK_SOLANA_GREEN = "#14F195"

SVG_NS = "http://www.w3.org/2000/svg"

# --------------------------------------------------------------------------- #
#  palette  (print ink definitions live in tools/build_artwork.py)
# --------------------------------------------------------------------------- #


@dataclass
class Doc:
    """Minimal SVG document builder (y grows downward, units = mm)."""

    width: float
    height: float
    body: list[str] = field(default_factory=list)
    defs: list[str] = field(default_factory=list)
    _counter: int = 0

    def uid(self, stem: str = "id") -> str:
        self._counter += 1
        return f"{stem}_{self._counter}"

    def add(self, markup: str) -> None:
        self.body.append(markup)

    def add_def(self, markup: str) -> None:
        self.defs.append(markup)

    trace: list = field(default_factory=list)   # logo placement provenance
    fonts: list = field(default_factory=list)   # font files used (outlined)
    ink_note: str = ""
    color_map: dict = None          # optional {hex -> hex} ink remap (1-colour builds)
    gradient_mode: str = "keep"     # keep | flat | hard2
    gradient_colors: tuple = ()     # colours for flat / hard2 modes

    def ink(self, color: str) -> str:
        if self.color_map:
            return self.color_map.get(color.lower(), self.color_map.get(color, color))
        return color

    def path(self, d: str, fill: str, *, opacity: float = 1.0, rule: str = "evenodd") -> None:
        op = "" if opacity >= 0.999 else f' fill-opacity="{opacity:.3f}"'
        self.add(
            f'<path d="{d}" fill="{self.ink(fill)}" fill-rule="{rule}"{op}/>'
        )

    def group(self, markup: str, attrs: str = "") -> None:
        self.add(f"<g {attrs}>{markup}</g>")

    def header_comment(self) -> str:
        """Provenance block embedded in the SVG so the printer can audit the file."""
        import hashlib
        lines = ["<!--",
                 "  SuperteamTR T-Shirt artwork - generated by tools/build_artwork.py",
                 f"  print size: {self.width:g} x {self.height:g} mm (1 SVG unit = 1 mm)",
                 "  all visible type is converted to outlines (no fonts required)",
                 ]
        if self.fonts:
            lines.append("  typefaces used (outlined): " + ", ".join(sorted(set(self.fonts))))
        if self.ink_note:
            lines.append("  inks: " + self.ink_note)
        if self.trace:
            lines.append("  official brand assets embedded (unmodified, rigid transform):")
            for t in self.trace:
                lines.append(
                    f"    - {t['asset']}  sha256:{t['sha256']}  "
                    f"placed {t['width']:.1f} x {t['height']:.1f} mm at "
                    f"({t['x']:.1f}, {t['y']:.1f})  mode={t['mode']}")
        lines.append("-->")
        return "\n".join(lines)

    def svg(self, bg: str | None = None) -> str:
        defs = ""
        if self.defs:
            defs = "<defs>" + "".join(self.defs) + "</defs>"
        back = ""
        if bg:
            back = f'<rect x="0" y="0" width="{self.width:g}" height="{self.height:g}" fill="{bg}"/>'
        return (
            f'<svg xmlns="{SVG_NS}" xmlns:xlink="http://www.w3.org/1999/xlink" '
            f'width="{self.width:g}mm" height="{self.height:g}mm" '
            f'viewBox="0 0 {self.width:g} {self.height:g}">\n'
            f"{self.header_comment()}\n{defs}\n{back}\n" + "\n".join(self.body) + "\n</svg>\n"
        )


# --------------------------------------------------------------------------- #
#  number formatting
# --------------------------------------------------------------------------- #


def n(v: float) -> str:
    s = f"{v:.3f}".rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


# --------------------------------------------------------------------------- #
#  geometry helpers -- all outputs are closed, fillable path data
# --------------------------------------------------------------------------- #


def _arc_cubics(cx: float, cy: float, r: float, a0: float, a1: float) -> list[tuple]:
    """Circular arc -> list of cubic bezier control points.

    Angles in degrees, measured clockwise from 12 o'clock (screen convention:
    y grows downward, so we mirror sin).
    """
    sweep = a1 - a0
    if abs(sweep) < 1e-9:
        return []
    segs = max(1, int(math.ceil(abs(sweep) / 90.0)))
    step = sweep / segs
    kappa = 4.0 / 3.0 * math.tan(math.radians(step) / 4.0)

    def pt(a: float) -> tuple[float, float]:
        ra = math.radians(a)
        return (cx + r * math.sin(ra), cy - r * math.cos(ra))

    out = []
    for i in range(segs):
        a = a0 + i * step
        b = a + step
        p0, p3 = pt(a), pt(b)

        def tangent(ang: float) -> tuple[float, float]:
            ra = math.radians(ang)
            return (math.cos(ra), math.sin(ra))  # d/da of (sin, -cos)

        t0 = tangent(a)
        t3 = tangent(b)
        p1 = (p0[0] + kappa * r * t0[0], p0[1] + kappa * r * t0[1])
        p2 = (p3[0] - kappa * r * t3[0], p3[1] - kappa * r * t3[1])
        out.append((p0, p1, p2, p3))
    return out


def _arc_d(cx: float, cy: float, r: float, a0: float, a1: float, start: bool = False) -> str:
    segs = _arc_cubics(cx, cy, r, a0, a1)
    if not segs:
        return ""
    d = ""
    if start:
        d += f"M{n(segs[0][0][0])} {n(segs[0][0][1])}"
    for _, p1, p2, p3 in segs:
        d += f"C{n(p1[0])} {n(p1[1])} {n(p2[0])} {n(p2[1])} {n(p3[0])} {n(p3[1])}"
    return d


def circle_d(cx: float, cy: float, r: float) -> str:
    return _arc_d(cx, cy, r, 0, 360, start=True) + "Z"


def ring_d(cx: float, cy: float, r_out: float, r_in: float) -> str:
    """Full annulus (donut). Inner contour reversed so even-odd / non-zero both work."""
    outer = _arc_d(cx, cy, r_out, 0, 360, start=True) + "Z"
    inner = _arc_d(cx, cy, r_in, 360, 0, start=True) + "Z"
    return outer + inner


def arc_band_d(cx: float, cy: float, r_out: float, r_in: float, a0: float, a1: float) -> str:
    """Annular sector (arc band) between two radii, swept a0 -> a1 (clockwise)."""
    o = _arc_d(cx, cy, r_out, a0, a1, start=True)
    px, py = _polar(cx, cy, r_in, a1)
    inner = _arc_d(cx, cy, r_in, a1, a0, start=False)   # starts with 'C' -> safe to concat
    return f"{o}L{n(px)} {n(py)}{inner}Z"


def _polar(cx: float, cy: float, r: float, ang: float) -> tuple[float, float]:
    ra = math.radians(ang)
    return (cx + r * math.sin(ra), cy - r * math.cos(ra))


def dot_d(cx: float, cy: float, r: float) -> str:
    return circle_d(cx, cy, r)


def bar_d(x0: float, y0: float, x1: float, y1: float, w: float) -> str:
    """Filled round-capped? No: square-capped bar between two points with width w."""
    dx, dy = x1 - x0, y1 - y0
    L = math.hypot(dx, dy) or 1.0
    ux, uy = dx / L, dy / L
    px, py = -uy * w / 2.0, ux * w / 2.0
    return (
        f"M{n(x0 + px)} {n(y0 + py)}"
        f"L{n(x1 + px)} {n(y1 + py)}"
        f"L{n(x1 - px)} {n(y1 - py)}"
        f"L{n(x0 - px)} {n(y0 - py)}Z"
    )


def rect_d(x: float, y: float, w: float, h: float, r: float = 0.0) -> str:
    """Rectangle (clockwise). Only M/L/C/Z commands are emitted so that the
    production exporters never have to resolve shorthand commands."""
    if r <= 0:
        return (
            f"M{n(x)} {n(y)}L{n(x + w)} {n(y)}L{n(x + w)} {n(y + h)}"
            f"L{n(x)} {n(y + h)}Z"
        )
    r = min(r, w / 2, h / 2)
    k = r * 0.5523
    return (
        f"M{n(x + r)} {n(y)}L{n(x + w - r)} {n(y)}"
        f"C{n(x + w - r + k)} {n(y)} {n(x + w)} {n(y + r - k)} {n(x + w)} {n(y + r)}"
        f"L{n(x + w)} {n(y + h - r)}"
        f"C{n(x + w)} {n(y + h - r + k)} {n(x + w - r + k)} {n(y + h)} {n(x + w - r)} {n(y + h)}"
        f"L{n(x + r)} {n(y + h)}"
        f"C{n(x + r - k)} {n(y + h)} {n(x)} {n(y + h - r + k)} {n(x)} {n(y + h - r)}"
        f"L{n(x)} {n(y + r)}"
        f"C{n(x)} {n(y + r - k)} {n(x + r - k)} {n(y)} {n(x + r)} {n(y)}Z"
    )


def arch_contour_d(w: float, h: float, base: float = 0.0) -> str:
    """Single closed contour of a stadium 'arch portal' (squared base,
    semicircular crown).  Local space: x centred on 0, base at y=base,
    the portal grows upward (negative y).  Width w = 2*r, height h >= w/2."""
    r = w / 2.0
    shoulder = base - h + r            # centre of the crown circle
    d = f"M{n(-r)} {n(base)}L{n(-r)} {n(shoulder)}"
    d += _arc_d(0.0, shoulder, r, 270.0, 450.0)   # left -> crown -> right
    d += f"L{n(r)} {n(base)}Z"
    return d


def _arch_local(w: float, h: float, t: float, y0: float = 0.0) -> str:
    """Outline of a stadium arch portal of wall thickness t (ring-like, filled)."""
    return arch_contour_d(w, h, y0) + arch_contour_d(w - 2 * t, h - t, y0)


def arcade_band_d(
    cx: float,
    cy: float,
    r_in: float,
    r_out: float,
    count: int,
    hole_w: float,
    hole_h: float,
    *,
    hole_base: float | None = None,
    skip: tuple[float, ...] = (),
    skip_tol: float = 0.0,
) -> str:
    """Colosseum arcade seen from above: an annular band with `count` arched
    openings knocked out of it (fill with rule='evenodd')."""
    from .pathparse import transform_d

    d = ring_d(cx, cy, r_out, r_in)
    base = r_in if hole_base is None else hole_base
    for i in range(count):
        a = i * 360.0 / count
        if skip and min(abs(((a - s + 180.0) % 360.0) - 180.0) for s in skip) <= skip_tol:
            continue
        px, py = _polar(cx, cy, base, a)
        rad = math.radians(a)
        ca, sa = math.cos(rad), math.sin(rad)
        d += transform_d(arch_contour_d(hole_w, hole_h), (ca, sa, -sa, ca, px, py))
    return d


@dataclass
class Place:
    """2D affine placement for local-space geometry."""

    x: float = 0.0
    y: float = 0.0
    rot: float = 0.0  # degrees, clockwise (screen)
    scale: float = 1.0

    def pt(self, px: float, py: float) -> tuple[float, float]:
        a = math.radians(self.rot)
        ca, sa = math.cos(a), math.sin(a)
        sx, sy = px * self.scale, py * self.scale
        return (self.x + sx * ca - sy * sa, self.y + sx * sa + sy * ca)


# --------------------------------------------------------------------------- #
#  text -> outlines
# --------------------------------------------------------------------------- #


class Shaper:
    """HarfBuzz shaping + fontTools outlines. Optionally instantiate a weight."""

    def __init__(self, font_path: str, weight: float | None = None, cache_key: str = ""):
        self.font_path = font_path
        self.weight = weight
        raw = open(font_path, "rb").read()
        self.tt = TTFont(font_path)
        if weight is not None and "fvar" in self.tt:
            self.tt = instantiateVariableFont(self.tt, {"wght": float(weight)})
        self.glyph_set = self.tt.getGlyphSet()
        self.upem = self.tt["head"].unitsPerEm
        self.order = self.tt.getGlyphOrder()
        self.hbfont = hb.Font(hb.Face(raw))
        if weight is not None:
            self.hbfont.set_variations({"wght": float(weight)})

    # -- shaping ---------------------------------------------------------- #
    def glyphs(self, text: str, size: float, tracking: float = 0.0):
        """Return [(gid, x, y, advance)] in mm units at the requested size."""
        buf = hb.Buffer()
        buf.add_str(text)
        buf.guess_segment_properties()
        hb.shape(self.hbfont, buf)
        s = size / self.upem
        out, x = [], 0.0
        for info, pos in zip(buf.glyph_infos, buf.glyph_positions):
            out.append((info.codepoint, x + pos.x_offset * s, -pos.y_offset * s, pos.x_advance * s))
            x += pos.x_advance * s + tracking
        return out, (x - tracking if out else 0.0)

    def measure(self, text: str, size: float, tracking: float = 0.0) -> float:
        return self.glyphs(text, size, tracking)[1]

    def path(
        self,
        text: str,
        size: float,
        *,
        x: float = 0.0,
        baseline: float = 0.0,
        tracking: float = 0.0,
        anchor: str = "start",
    ) -> tuple[str, float]:
        """Outlined path data (y-down) + advance width."""
        gly, width = self.glyphs(text, size, tracking)
        if anchor == "middle":
            x -= width / 2.0
        elif anchor == "end":
            x -= width
        s = size / self.upem
        chunks = []
        for gid, gx, gy, _adv in gly:
            name = self.order[gid]
            pen = SVGPathPen(self.glyph_set)
            # font units -> mm, with a y-flip because font design space is y-up
            tpen = TransformPen(pen, Transform(s, 0, 0, -s, x + gx, baseline + gy))
            self.glyph_set[name].draw(tpen)
            d = pen.getCommands()
            if d:
                chunks.append(d)
        return (" ".join(chunks), width)

    def circular_path(
        self,
        text: str,
        *,
        cx: float,
        cy: float,
        radius: float,
        size: float,
        tracking: float = 0.0,
        start_angle: float = 0.0,
        direction: int = 1,
        flip: bool = False,
    ) -> str:
        """Text set around a circle (angles clockwise from 12 o'clock)."""
        gly, width = self.glyphs(text, size, tracking)
        ang0 = start_angle - (width / radius) * (180.0 / math.pi) / 2.0 * direction
        s = size / self.upem
        chunks = []
        for gid, gx, gy, _adv in gly:
            name = self.order[gid]
            # angle on the circle for this glyph's origin
            frac = gx / radius * (180.0 / math.pi) * direction
            ang = ang0 + frac
            px, py = _polar(cx, cy, radius, ang)
            rot = ang + (180.0 if flip else 0.0)
            a = math.radians(rot)
            ca, sa = math.cos(a), math.sin(a)
            pen = SVGPathPen(self.glyph_set)
            # font space is y-up, the artwork is y-down: mirror y, then rotate
            # clockwise by `rot` so glyph tops face outwards (or inwards when flipped)
            tpen = TransformPen(
                pen,
                Transform(s * ca, s * sa, s * sa, -s * ca, px, py),
            )
            self.glyph_set[name].draw(tpen)
            d = pen.getCommands()
            if d:
                chunks.append(d)
        return " ".join(chunks)


# --------------------------------------------------------------------------- #
#  official brand SVG import
# --------------------------------------------------------------------------- #

_TRANSFORM_RE = re.compile(r"(matrix|translate|scale|rotate|skewX|skewY)\s*\(([^)]*)\)")


def _parse_transform(s: str) -> tuple[float, float, float, float, float, float]:
    m = (1.0, 0.0, 0.0, 1.0, 0.0, 0.0)
    for kind, args in _TRANSFORM_RE.findall(s or ""):
        vals = [float(v) for v in re.split(r"[\s,]+", args.strip()) if v]
        if kind == "matrix":
            t = tuple(vals[:6])  # type: ignore
        elif kind == "translate":
            t = (1, 0, 0, 1, vals[0], vals[1] if len(vals) > 1 else 0)
        elif kind == "scale":
            sx = vals[0]
            sy = vals[1] if len(vals) > 1 else sx
            t = (sx, 0, 0, sy, 0, 0)
        elif kind == "rotate":
            a = math.radians(vals[0])
            ca, sa = math.cos(a), math.sin(a)
            t = (ca, sa, -sa, ca, 0, 0)
            if len(vals) == 3:
                cx, cy = vals[1], vals[2]
                t = _mul((1, 0, 0, 1, cx, cy), _mul(t, (1, 0, 0, 1, -cx, -cy)))
        elif kind == "skewX":
            t = (1, 0, math.tan(math.radians(vals[0])), 1, 0, 0)
        else:
            t = (1, math.tan(math.radians(vals[0])), 0, 1, 0, 0)
        m = _mul(m, t)  # type: ignore
    return m  # type: ignore


def _mul(a, b):
    a0, a1, a2, a3, a4, a5 = a
    b0, b1, b2, b3, b4, b5 = b
    return (
        a0 * b0 + a2 * b1,
        a1 * b0 + a3 * b1,
        a0 * b2 + a2 * b3,
        a1 * b2 + a3 * b3,
        a0 * b4 + a2 * b5 + a4,
        a1 * b4 + a3 * b5 + a5,
    )


@dataclass
class LogoAsset:
    source_path: str = ""
    paths: list[tuple[str, str]] = field(default_factory=list)  # (d, paint)
    gradients: dict[str, dict] = field(default_factory=dict)
    viewbox: tuple[float, float, float, float] = (0, 0, 1, 1)


def load_logo(path: str) -> LogoAsset:
    root = ET.parse(path).getroot()
    vb = [float(v) for v in re.split(r"[\s,]+", root.get("viewBox", "0 0 1 1").strip())]
    gradients: dict[str, dict] = {}
    paths: list[tuple[str, str]] = []

    def walk(el, ctm):
        tag = el.tag.split("}")[-1]
        if tag in ("g", "svg"):
            m = _mul(ctm, _parse_transform(el.get("transform", "")))
            for ch in el:
                walk(ch, m)
            return
        if tag == "linearGradient":
            gid = el.get("id")
            stops = []
            for st in el:
                if st.tag.split("}")[-1] == "stop":
                    col = st.get("stop-color") or (
                        re.search(r"stop-color:\s*([^;]+)", st.get("style", "") or "") or [None, "#000"]
                    )[1]
                    stops.append((float(st.get("offset", 0)), col.strip()))
            gradients[gid] = dict(
                stops=stops,
                x1=el.get("x1", "0"), y1=el.get("y1", "0"),
                x2=el.get("x2", "1"), y2=el.get("y2", "0"),
                units=el.get("gradientUnits", "objectBoundingBox"),
            )
            return
        if tag == "path":
            d = el.get("d")
            if not d:
                return
            paint = el.get("fill") or "none"
            if paint == "none":
                return
            paths.append((d, paint, _mul(ctm, _parse_transform(el.get("transform", "")))))  # type: ignore

    walk(root, (1, 0, 0, 1, 0, 0))
    return LogoAsset(source_path=path, paths=paths, gradients=gradients,
                     viewbox=(vb[0], vb[1], vb[2], vb[3]))  # type: ignore


def asset_sha256(path: str) -> str:
    import hashlib
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def place_logo(
    doc: Doc,
    asset: LogoAsset,
    *,
    x: float,
    y: float,
    width: float | None = None,
    height: float | None = None,
    align: str = "center",
    recolor: str | None = None,
    gradient_map: dict[str, str] | None = None,
) -> tuple[float, float]:
    """Place an official logo asset. Returns (placed_w, placed_h).

    recolor=None  -> keep original colours / gradients (unmodified brand asset)
    recolor=hex   -> single-colour (monochrome) usage for one-colour / two-colour print
    """
    vx, vy, vw, vh = asset.viewbox
    if width is None and height is None:
        raise ValueError("width or height required")
    if width is None:
        width = height * vw / vh  # type: ignore
    if height is None:
        height = width * vh / vw
    s = min(width / vw, height / vh)
    ox = x - (width * {"start": 0.0, "center": 0.5, "end": 1.0}[align])
    oy = y
    m = _mul((s, 0, 0, s, ox - vx * s, oy - vy * s), (1, 0, 0, 1, 0, 0))

    if getattr(asset, "source_path", None):
        doc.trace.append(dict(
            asset=os.path.basename(asset.source_path),
            sha256=asset_sha256(asset.source_path),
            x=round(ox, 2), y=round(oy, 2),
            width=round(width, 2), height=round(height, 2),
            mode="monochrome" if recolor else "full colour (original asset)",
        ))

    need_grads: set[str] = set()
    for d, paint, pm in asset.paths:
        # scale factor compensation: gradientUnits=userSpaceOnUse coords are in
        # the asset's own space, so we keep the same matrix for the paint server
        if recolor:
            fill = recolor
        elif paint.startswith("url(#"):
            gid = paint[5:-1]
            new_id = doc.uid("grad")
            need_grads.add(gid)
            fill = f"url(#{new_id})"
            grad = dict(asset.gradients.get(gid, {}))
            _emit_gradient(doc, grad, new_id, m, gradient_map,
                           mode=getattr(doc, "gradient_mode", "keep"),
                           colors=getattr(doc, "gradient_colors", ()))
        else:
            fill = paint
        doc.add(f'<path d="{_transform_d(d, _mul(pm, m))}" fill="{fill}" fill-rule="evenodd"/>')
    return (width, height)


def _emit_gradient(doc: Doc, grad: dict, new_id: str, m, gradient_map=None,
                   mode: str = "keep", colors: tuple = ()) -> None:
    stops = grad.get("stops") or [(0, "#9945FF"), (1, "#14F195")]
    if mode == "flat":
        col = colors[0] if colors else INK_SOLANA_PURPLE
        stops = [(0, col), (1, col)]
    elif mode == "hard2":
        c1 = colors[0] if colors else INK_SOLANA_PURPLE
        c2 = colors[1] if len(colors) > 1 else INK_SOLANA_GREEN
        stops = [(0, c1), (0.5, c1), (0.5, c2), (1, c2)]
    if gradient_map:
        stops = [(o, gradient_map.get(c.lower(), c)) for o, c in stops]
    def _f(key, default):
        raw = grad.get(key, default)
        try:
            return float(raw)
        except (TypeError, ValueError):
            return float(default)

    if grad.get("units") == "userSpaceOnUse":
        x1, y1, x2, y2 = _f("x1", 0), _f("y1", 0), _f("x2", 1), _f("y2", 0)
    else:
        # objectBoundingBox percentages -> approximate with the asset's own
        # coordinates (all supplied Solana assets are userSpaceOnUse anyway)
        x1, y1, x2, y2 = _f("x1", 0), _f("y1", 0), _f("x2", 1), _f("y2", 0)
    a0, a1, a2, a3, a4, a5 = m
    p1 = (a0 * x1 + a2 * y1 + a4, a1 * x1 + a3 * y1 + a5)
    p2 = (a0 * x2 + a2 * y2 + a4, a1 * x2 + a3 * y2 + a5)
    coords = f'x1="{n(p1[0])}" y1="{n(p1[1])}" x2="{n(p2[0])}" y2="{n(p2[1])}"'
    units = 'gradientUnits="userSpaceOnUse"'
    body = "".join(
        f'<stop offset="{o:g}" stop-color="{c}"/>' for o, c in stops
    )
    doc.add_def(f'<linearGradient id="{new_id}" {coords} {units}>{body}</linearGradient>')


def frame_d(x: float, y: float, w: float, h: float, t: float) -> str:
    """Rectangular frame (rect ring) built from an outer + reversed inner contour."""
    outer = rect_d(x, y, w, h)
    ix, iy, iw, ih = x + t, y + t, w - 2 * t, h - 2 * t
    inner = (
        f"M{n(ix)} {n(iy)}V{n(iy + ih)}H{n(ix + iw)}V{n(iy)}Z"
    )
    return outer + inner
